ignore:
#  - ".*/data/.*"  # ignore folders and all its contents
#  - ".*/entity/.*" # ignore folders and all its contents
  - ".*/config/.*" # ignore folders and all its contents
  - ".*/ApplicationConfig.*