spring:
  application:
    name: fwmt-resource-service

  jpa.properties.hibernate.default_schema: gateway
  datasource:
    username: ${cloud.services.postgresql.connection.username}
    password: ${cloud.services.postgresql.connection.password}
    url: ${cloud.services.postgresql.connection.jdbcurl}
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    schema: classpath:/schema-cloud.sql

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema: gateway
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:db/changelog/db.changelog-master.yaml

security.user:
  name: name
  password: password

