info:
  name: @project.artifactId@
  version: @project.version@
  origin: @scm.url@
  commit: @buildNumber@
  branch: @scmBranch@
  built: @timestamp@

server:
  contextPath: /resources
  port: 9095

spring:
  http.multipart:
    max-file-size: 12800MB
    max-request-size: 12800MB
  datasource:
    url: jdbc:postgresql://localhost/postgres?currentSchema=gateway
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: false
    username: postgres
    password: postgres
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management.endpoint.health.show-details: always

liquibase:
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gateway
  default-schema: gateway
  user: postgres
  password: postgres

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

security.user:
  name: user
  password: password